

Parish.create!(name: 'Castel')
Parish.create!(name: 'Forest')
Parish.create!(name: 'St Andrew')
Parish.create!(name: 'St Martin')
Parish.create!(name: 'St Peter Port')
Parish.create!(name: 'St Pierre du Bois')
Parish.create!(name: 'St Sampson')
Parish.create!(name: 'St Saviour')
Parish.create!(name: 'Torteval')
Parish.create!(name: 'Vale')

gg = Place.create!(name: 'Guernsey', code: 'GG')
je = Place.create!(name: 'Jersey', code: 'JE')

buses = DataCategory.create!(name: 'Buses', stub: 'buses', desc: 'Monthly usage of buses since 2011', image: 'i-814-bus-2x')
crime = DataCategory.create!(name: 'Crime', stub: 'crime', desc: 'Detailed crime data from published reports', image: 'i-828-shield-2x')
earnings = DataCategory.create!(name: 'Earnings', stub: 'earnings', desc: 'Earnings by age group, sector, and sex', image: 'i-826-money-1-2x')
education = DataCategory.create!(name: 'Education', stub: 'education', desc: 'Post-16 results, overall GCSE grades and GCSE grades by school', image: 'i-897-graduation-cap-2x')
emissions = DataCategory.create!(name: 'Emissions', stub: 'emissions', desc: 'Emissions from published reports', image: 'i-1022-factory-2x')
employment = DataCategory.create!(name: 'Employment', stub: 'employment', desc: 'Employment data from published reports', image: 'i-780-building-2x')
energy = DataCategory.create!(name: 'Energy', stub: 'energy', desc: 'Electricity, nuclear, oil, gas, etc.', image: 'i-965-lightning-bolt-2x')
finance = DataCategory.create!(name: 'Finance', stub: 'finance', desc: 'Finance industry stats', image: 'i-827-money-2-2x')
fire_and_rescue = DataCategory.create!(name: 'Fire & Rescue', stub: 'fire_and_rescue', desc: 'Things the Fire & Rescue department deal with', image: 'i-923-spray-can-2x')
health = DataCategory.create!(name: 'Health', stub: 'health', desc: 'Health data from Chest & Heart screenings and government', image: 'i-892-bandaid-2x')
housing = DataCategory.create!(name: 'Housing', stub: 'housing', desc: 'Detailed quarterly house prices since 1981 to today', image: 'i-750-home-2x')
inflation = DataCategory.create!(name: 'Inflation', stub: 'inflation', desc: 'RPI & RPIX inflation data from 1949', image: 'i-754-scale-2x')
overseas_aid = DataCategory.create!(name: 'Overseas Aid', stub: 'overseas_aid', desc: 'Aid and emergency relief sent overseas', image: 'i-950-ekg-2x')
population = DataCategory.create!(name: 'Population', stub: 'population', desc: 'Guernsey population data from published reports', image: 'i-895-user-group-2x')
sailings = DataCategory.create!(name: 'Sailings', stub: 'sailings', desc: 'Sailing details refreshed on the fly from the Guernsey Harbour', image: 'i-1094-sail-boat-2-2x')
tourism = DataCategory.create!(name: 'Tourism', stub: 'tourism', desc: 'Incoming visitors', image: 'i-881-globe-2x')
traffic = DataCategory.create!(name: 'Traffic', stub: 'traffic', desc: 'Traffic data from published reports', image: 'i-815-car-2x')
transport = DataCategory.create!(name: 'Transport', stub: 'transport', desc: 'Vehicle usage', image: 'i-917-speedometer-2x')
water = DataCategory.create!(name: 'Water', stub: 'water', desc: 'Water data from published reports', image: 'i-934-measuring-cup-2x')
weather = DataCategory.create!(name: 'Weather', stub: 'weather', desc: 'Weather from published reports', image: 'i-862-sun-cloud-2x')
flights = DataCategory.create!(name: 'Flights', stub: 'flights', desc: 'Flight details refreshed on the fly from the Guernsey Airport', image: 'i-893-airplane-2x')
tides = DataCategory.create!(name: 'Tides', stub: 'tides', desc: 'Coming soon', image: 'i-958-life-preserver-2x')
fuel = DataCategory.create!(name: 'Fuel', stub: 'fuel', desc: 'Coming soon', image: 'i-931-gas-pump-2x')
sports = DataCategory.create!(name: 'Sports', stub: 'sports', desc: 'Coming soon', image: 'i-1090-ping-pong-paddle-2x')
broadband = DataCategory.create!(name: 'Broadband', stub: 'broadband', desc: 'Coming soon', image: 'i-937-wifi-signal-2x')
recycling = DataCategory.create!(name: 'Recycling', stub: 'recycling', desc: 'Coming soon', image: 'i-776-recycle-2x')
roadworks = DataCategory.create!(name: 'Roadworks', stub: 'roadworks', desc: 'Coming soon', image: 'i-1032-route-2x')
fishing = DataCategory.create!(name: 'Fishing', stub: 'fishing', desc: 'Coming soon', image: 'i-1029-fish-2x')

DataSet.create!(place: gg, data_category: buses, name: 'Usage', stub: 'usage', desc: 'Bus usage by year and month from 2011', filename: 'buses/bus_usage.json', live: false, source_url: 'http://www.gov.gg/PublicTransport')
DataSet.create!(place: gg, data_category: crime, name: 'Crimes', stub: 'crimes', desc: 'Crime by offence since 2005', filename: 'crime/crime.json', live: false, source_url: 'http://www.guernsey.police.uk/article/6078/Publications')
DataSet.create!(place: gg, data_category: crime, name: 'Prison Population', stub: 'prison_population', desc: 'Number of people in the prison', filename: 'crime/prison_population.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: crime, name: 'Worried', stub: 'worried', desc: 'Percentage of people worried about crime from a survey', filename: 'crime/worried.json', live: false, source_url: 'http://www.guernsey.police.uk/article/6078/Publications')
DataSet.create!(place: gg, data_category: traffic, name: 'Traffic', stub: 'traffic', desc: 'Traffic incidents by offence and year', filename: 'traffic/traffic.json', live: false, source_url: 'http://www.guernsey.police.uk/article/6078/Publications')
DataSet.create!(place: gg, data_category: traffic, name: 'Collisions', stub: 'collisions', desc: 'Traffic collisions by year', filename: 'traffic/traffic_collisions.json', live: false, source_url: 'http://www.guernsey.police.uk/article/6078/Publications')
DataSet.create!(place: gg, data_category: traffic, name: 'Injuries', stub: 'injuries', desc: 'Traffic injuries by type and extent of injury', filename: 'traffic/traffic_injuries.json', live: false, source_url: 'http://www.guernsey.police.uk/article/6078/Publications')
DataSet.create!(place: gg, data_category: traffic, name: 'Classifications', stub: 'classifications', desc: 'Traffic injury classifications (fatal, serious, slight)', filename: 'traffic/traffic_classifications.json', live: false, source_url: 'http://www.guernsey.police.uk/article/6078/Publications')
DataSet.create!(place: gg, data_category: housing, name: 'Local Prices', stub: 'local_prices', desc: 'House prices by quarter since 1981 includes numerous stats', filename: 'houses/local_prices.json', live: false, source_url: 'http://gov.gg/article/112353/Quarterly-Residential-Property-Prices-and-Annual-Housing-Stock-Bulletins-2014')
DataSet.create!(place: gg, data_category: housing, name: 'Open Prices', stub: 'open_prices', desc: 'House prices by quarter since 1981 includes numerous stats', filename: 'houses/open_prices.json', live: false, source_url: 'http://gov.gg/article/112353/Quarterly-Residential-Property-Prices-and-Annual-Housing-Stock-Bulletins-2014')
DataSet.create!(place: gg, data_category: housing, name: 'Bedrooms', stub: 'bedrooms', desc: 'Total bedrooms per unit with market since 2011', filename: 'houses/bedrooms.json', live: false, source_url: 'http://gov.gg/property')
DataSet.create!(place: gg, data_category: housing, name: 'Types', stub: 'types', desc: 'Total units with market and type for 2014', filename: 'houses/types.json', live: false, source_url: 'http://gov.gg/property')
DataSet.create!(place: gg, data_category: housing, name: 'Units', stub: 'units', desc: 'Total units by market since 2010', filename: 'houses/units.json', live: false, source_url: 'http://gov.gg/property')
DataSet.create!(place: gg, data_category: flights, name: 'Arrivals', stub: 'arrivals', desc: 'Live arrival data from the Guernsey Airport', filename: 'get_flights_arrivals', live: true, source_url: 'https://www.airport.gg/arrivals-departures')
DataSet.create!(place: gg, data_category: flights, name: 'Departures', stub: 'departures', desc: 'Live departure data from the Guernsey Airport', filename: 'get_flights_departures', live: true, source_url: 'https://www.airport.gg/arrivals-departures')
DataSet.create!(place: gg, data_category: sailings, name: 'Harbour', stub: 'harbour', desc: 'Live sailings data from the Guernsey Harbour. Includes both arrivals and departures', filename: 'get_harbour_sailings', live: true, source_url: 'http://www.guernseyharbours.gov.gg/article/100192/Arrivals--Departures')
DataSet.create!(place: gg, data_category: sailings, name: 'Condor Punctuality', stub: 'condor_punctuality', desc: 'Condor punctuality from published reports', filename: 'sailings/condor_punctuality.json', live: false, source_url: 'http://www.condorferries.co.uk/performance/punctuality-reports.aspx')
DataSet.create!(place: gg, data_category: sailings, name: 'Cruises', stub: 'cruises', desc: 'Visiting cruise ships', filename: 'sailings/cruises.json', live: false, source_url: 'http://www.guernseyharbours.gov.gg/CHttpHandler.ashx?id=93382&p=0')
DataSet.create!(place: gg, data_category: education, name: 'Post 16 Results', stub: 'post16results', desc: 'Post 16 results since 2010 by type, grade and percentage', filename: 'education/post16results.json', live: false, source_url: 'http://www.education.gg/')
DataSet.create!(place: gg, data_category: education, name: 'GCSE Overall', stub: 'gcse_overall', desc: 'GCSE overall since 2009 by result and percentage', filename: 'education/gcse_overall.json', live: false, source_url: 'http://www.education.gg/')
DataSet.create!(place: gg, data_category: education, name: 'GCSE School', stub: 'gcse_school', desc: 'GCSE results for schools since 2010 by result and percentage', filename: 'education/gcse_school.json', live: false, source_url: 'http://www.education.gg/')
DataSet.create!(place: gg, data_category: education, name: 'Students in UK', stub: 'students_in_uk', desc: 'Students studying in the UK', filename: 'education/students_in_uk.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: population, name: 'Population', stub: 'population', desc: 'Population values by year, sex and age. Ages are in ranges.', filename: 'population/population.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'Age', stub: 'age', desc: 'Population values by year and age. Individual year ages. Mixed sex.', filename: 'population/age.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'Age Male', stub: 'age_male', desc: 'Population values by year and age. Individual year ages. Male only.', filename: 'population/age_male.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'Age Female', stub: 'age_female', desc: 'Population values by year and age. Individual year ages. Female only.', filename: 'population/age_female.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'Birthplace', stub: 'birthplace', desc: 'Population by birthplace.', filename: 'population/birthplace.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'Changes', stub: 'changes', desc: 'Population changes by quarter. Has births, deaths, immigration and emigration.', filename: 'population/changes.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'District', stub: 'district', desc: 'Population by voting district.', filename: 'population/district.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: population, name: 'Parish', stub: 'parish', desc: 'Population by parish.', filename: 'population/parish.json', live: false, source_url: 'http://www.gov.gg/population')
DataSet.create!(place: gg, data_category: earnings, name: 'Earnings Age Group', stub: 'earnings_age_group', desc: 'Earnings by age group since 2012, includes lower quartile, median and upper quartile.', filename: 'earnings/earnings_age_group.json', live: false, source_url: 'http://www.gov.gg/earnings')
DataSet.create!(place: gg, data_category: earnings, name: 'Earnings Sector', stub: 'earnings_sector', desc: 'Earnings by sector since 2012, includes lower quartile, median and upper quartile.', filename: 'earnings/earnings_sector.json', live: false, source_url: 'http://www.gov.gg/earnings')
DataSet.create!(place: gg, data_category: earnings, name: 'Earnings Sex', stub: 'earnings_sex', desc: 'Earnings by sex since 2005, includes nominal and real.', filename: 'earnings/earnings_sex.json', live: false, source_url: 'http://www.gov.gg/earnings')
DataSet.create!(place: gg, data_category: inflation, name: 'Changes', stub: 'changes', desc: 'RPI & RPIX changes since 1949', filename: 'inflation/changes.json', live: false, source_url: 'http://www.gov.gg/rpi')
DataSet.create!(place: gg, data_category: inflation, name: 'RPI Group Changes', stub: 'rpi_group_changes', desc: 'RPI group changes since Q4 2004', filename: 'inflation/rpi_group_changes.json', live: false, source_url: 'http://www.gov.gg/rpi')
DataSet.create!(place: gg, data_category: inflation, name: 'RPIX Group Changes', stub: 'rpix_group_changes', desc: 'RPIX group changes since Q4 2014', filename: 'inflation/rpix_group_changes.json', live: false, source_url: 'http://www.gov.gg/rpi')
DataSet.create!(place: gg, data_category: water, name: 'Domestic Consumption', stub: 'domestic_consumption', desc: 'Domestic water consumption since 2008 in ML', filename: 'water/domestic_consumption.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: emissions, name: 'Types', stub: 'types', desc: 'Emissions since 1990 by type in kt for Carbon Dioxide and kt of CO2 equivalent for others', filename: 'emissions/type.json', live: false, source_url: 'http://www.gov.gg/ghg')
DataSet.create!(place: gg, data_category: employment, name: 'Totals', stub: 'totals', desc: 'Employed, unemployed and employer totals since Q4 2012 (missing Q4 2012 employed)', filename: 'employment/totals.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: weather, name: 'Annual', stub: 'annual', desc: 'Annual weather stats from 2010', filename: 'weather/metoffice_annual_report.json', live: false, source_url: 'http://www.metoffice.gov.gg/annualwxreports.html')
DataSet.create!(place: gg, data_category: weather, name: 'Monthly', stub: 'monthly', desc: 'Monthly weather stats from Jan 2010', filename: 'weather/metoffice_monthly_report.json', live: false, source_url: 'http://www.metoffice.gov.gg/annualwxreports.html')
DataSet.create!(place: gg, data_category: weather, name: 'Frost Days', stub: 'frost_days', desc: 'Frost days since 1946 (below 0°C)', filename: 'weather/frost_days.json', live: false, source_url: 'http://www.metoffice.gov.gg/annualwxreports.html')
DataSet.create!(place: gg, data_category: finance, name: 'Banking', stub: 'banking', desc: 'Banking data', filename: 'finance/banking.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: health, name: 'Concerns', stub: 'concerns', desc: 'Concerns found during screenings', filename: 'health/chest_and_heart_concerns.json', live: false, source_url: 'http://www.chestandheart.org.gg/')
DataSet.create!(place: gg, data_category: health, name: 'Totals', stub: 'totals', desc: 'Total numbers of screenings by age', filename: 'health/chest_and_heart_totals.json', live: false, source_url: 'http://www.chestandheart.org.gg/')
DataSet.create!(place: gg, data_category: health, name: 'Medical Unit Bed Days Five Year Average', stub: 'med_unit_bed_days_five_yr_avg', desc: 'Medical Unit bed days five year average', filename: 'health/med_unit_bed_days_five_yr_avg.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: fire_and_rescue, name: 'Attendances', stub: 'attendances', desc: 'Attendances by Fire and Rescue services', filename: 'fire_and_rescue/attendances.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: overseas_aid, name: 'Contributions', stub: 'contributions', desc: 'Aid and emergency relief sent overseas', filename: 'overseas_aid/contributions.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: tourism, name: 'Cruises', stub: 'cruises', desc: 'Incoming cruise passengers', filename: 'tourism/cruises.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: tourism, name: 'Air by Month', stub: 'air_by_month', desc: 'Incoming air passengers by month', filename: 'tourism/air_by_month.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: tourism, name: 'Sea by Month', stub: 'sea_by_month', desc: 'Incoming sea passengers by month', filename: 'tourism/sea_by_month.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: energy, name: 'Electricity Consumption', stub: 'electricity_consumption', desc: 'Domestic and commercial electricity consumption', filename: 'energy/electricity_consumption.json', live: false, source_url: 'http://www.gov.gg/pru')
DataSet.create!(place: gg, data_category: energy, name: 'Electricity Import vs Generated', stub: 'electricity_import_vs_generated', desc: 'Imported vs generated electricity', filename: 'energy/electricity_import_vs_generated.json', live: false, source_url: 'http://electricity.gg/')
DataSet.create!(place: gg, data_category: transport, name: 'Registered Vehicles', stub: 'registered_vehicles', desc: 'Registered vehicles', filename: 'transport/registered_vehicles.json', live: false, source_url: 'http://www.gov.gg/pru')

# Uncomment for a test admin user
#test_user = User.create!(email: 'test@data.gg', password: 'password',
#  password_confirmation: 'password', forename: 'Test', surname: 'User', is_admin: true)