Parish.create!(name: 'Castel')
Parish.create!(name: 'Forest')
Parish.create!(name: 'St Andrew')
Parish.create!(name: 'St Martin')
Parish.create!(name: 'St Peter Port')
Parish.create!(name: 'St Pierre du Bois')
Parish.create!(name: 'St Sampson')
Parish.create!(name: 'St Saviour')
Parish.create!(name: 'Torteval')
Parish.create!(name: 'Vale')


DataCategory.create!(name: 'Buses', stub: 'buses', desc: 'Monthly usage of buses since 2011', image: 'i-814-bus-2x')
DataCategory.create!(name: 'Crime', stub: 'crime', desc: 'Detailed crime data from published reports', image: 'i-828-shield-2x')
DataCategory.create!(name: 'Earnings', stub: 'earnings', desc: 'Earnings by age group, sector, and sex', image: 'i-826-money-1-2x')
DataCategory.create!(name: 'Education', stub: 'education', desc: 'Post-16 results, overall GCSE grades and GCSE grades by school', image: 'i-897-graduation-cap-2x')
DataCategory.create!(name: 'Emissions', stub: 'emissions', desc: 'Emissions from published reports', image: 'i-1022-factory-2x')
DataCategory.create!(name: 'Employment', stub: 'employment', desc: 'Employment data from published reports', image: 'i-780-building-2x')
DataCategory.create!(name: 'Energy', stub: 'energy', desc: 'Electricity, nuclear, oil, gas, etc.', image: 'i-965-lightning-bolt-2x')
DataCategory.create!(name: 'Finance', stub: 'finance', desc: 'Finance industry stats', image: 'i-827-money-2-2x')
DataCategory.create!(name: 'Fire & Rescue', stub: 'fire_and_rescue', desc: 'Things the Fire & Rescue department deal with', image: 'i-923-spray-can-2x')
DataCategory.create!(name: 'Health', stub: 'health', desc: 'Health data from Chest & Heart screenings and government', image: 'i-892-bandaid-2x')
DataCategory.create!(name: 'Housing', stub: 'housing', desc: 'Detailed quarterly house prices since 1981 to today', image: 'i-750-home-2x')
DataCategory.create!(name: 'Inflation', stub: 'inflation', desc: 'RPI & RPIX inflation data from 1949', image: 'i-754-scale-2x')
DataCategory.create!(name: 'Overseas Aid', stub: 'overseas_aid', desc: 'Aid and emergency relief sent overseas', image: 'i-950-ekg-2x')
DataCategory.create!(name: 'Population', stub: 'population', desc: 'Guernsey population data from published reports', image: 'i-895-user-group-2x')
DataCategory.create!(name: 'Sailings', stub: 'sailings', desc: 'Sailing details refreshed on the fly from the Guernsey Harbour', image: 'i-1094-sail-boat-2-2x')
DataCategory.create!(name: 'Tourism', stub: 'tourism', desc: 'Incoming visitors', image: 'i-881-globe-2x')
DataCategory.create!(name: 'Traffic', stub: 'traffic', desc: 'Traffic data from published reports', image: 'i-815-car-2x')
DataCategory.create!(name: 'Transport', stub: 'transport', desc: 'Vehicle usage', image: 'i-917-speedometer-2x')
DataCategory.create!(name: 'Water', stub: 'water', desc: 'Water data from published reports', image: 'i-934-measuring-cup-2x')
DataCategory.create!(name: 'Weather', stub: 'weather', desc: 'Weather from published reports', image: 'i-862-sun-cloud-2x')
DataCategory.create!(name: 'Flights', stub: 'flights', desc: 'Flight details refreshed on the fly from the Guernsey Airport', image: 'i-893-airplane-2x')
DataCategory.create!(name: 'Tides', stub: 'tides', desc: 'Coming soon', image: 'i-958-life-preserver-2x')
DataCategory.create!(name: 'Fuel', stub: 'fuel', desc: 'Coming soon', image: 'i-931-gas-pump-2x')
DataCategory.create!(name: 'Sports', stub: 'sports', desc: 'Coming soon', image: 'i-1090-ping-pong-paddle-2x')
DataCategory.create!(name: 'Broadband', stub: 'broadband', desc: 'Coming soon', image: 'i-937-wifi-signal-2x')
DataCategory.create!(name: 'Recycling', stub: 'recycling', desc: 'Coming soon', image: 'i-776-recycle-2x')
DataCategory.create!(name: 'Roadworks', stub: 'roadworks', desc: 'Coming soon', image: 'i-1032-route-2x')
DataCategory.create!(name: 'Fishing', stub: 'fishing', desc: 'Coming soon', image: 'i-1029-fish-2x')


test_user = User.create!(email: 'test@data.gg', password: 'password', password_confirmation: 'password',
  forename: 'Test', surname: 'User', is_admin: true)